### ISSUE TITLE
提供一个激活程序的compose供大家使用

### ISSUE THREAD

**Issue by silence9527** [envyafish/AutoLadyIssue#47]
```
services:
  byte-muse-license:
    container_name: byte-muse-license
    image: envyafish/byte-muse-license:latest
    network_mode: bridge
    ports:
      - 5000:5000/tcp

```
