### ISSUE TITLE
容器的基镜像版本过低，导致虽然我有IPV6的能力，但是默认还是优先访问IPV4的地址（IPV6被BAN的几率小）

### ISSUE THREAD

**Issue by xspeed1989** [envyafish/AutoLadyIssue#69]
容器内请求
```
root@a005e0b27779:/# curl https://某Db.com/rankings/movies?t=censored&p=monthly
[1] 475
root@a005e0b27779:/# The owner of this website has banned your access based on your browser's behaving

IP: xx.xx.xx.xxx

基於你的異常行為，管理員禁止了你的訪問，將在3-7日後解除。
群組和反饋不受理此問題，請耐心等待解除或更換網絡節點進行訪問。
```

**同样的子网，jellyfin的容器可以默认使用IPV6请求并获取结果**

docker-compose.yml
```
services:
  aaa:
    image: envyafish/byte-muse:latest
    container_name: aaa
    restart: always
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
    networks:
      - ip6net
    ports:
      - "8043:80"
    volumes:
      - ./autolady:/data
networks:
  ip6net:
    enable_ipv6: true
```
